//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataFirstApproch
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTb1
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public Nullable<double> empSal { get; set; }
        public Nullable<int> deptid { get; set; }
    
        public virtual DeptTable DeptTable { get; set; }
    }
}
